/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmotor;

import java.awt.Component;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static rentalmotor.Rentalmotor.main;
public class adminlogin extends javax.swing.JFrame
/**
 *
 * @author Sakinah
 *//**
 *
 * @author Sakinah
 */
public class adminlogin extends javax.swing.JPanel {

    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfuname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfpwd = new javax.swing.JPasswordField();
        bsignin = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        bsignup = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RENTAL MOTOR 101 ADMIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 220, 30);

        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 90, 70, 20);
        jPanel1.add(tfuname);
        tfuname.setBounds(100, 120, 180, 30);

        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 180, 80, 20);
        jPanel1.add(tfpwd);
        tfpwd.setBounds(100, 210, 180, 30);

        bsignin.setText("SIGN IN");
        bsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsigninActionPerformed(evt);
            }
        });
        jPanel1.add(bsignin);
        bsignin.setBounds(270, 280, 90, 30);

        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel1.add(bexit);
        bexit.setBounds(140, 280, 90, 30);

        bsignup.setText("SIGN UP");
        bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsignupActionPerformed(evt);
            }
        });
        jPanel1.add(bsignup);
        bsignup.setBounds(10, 280, 90, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void bsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsigninActionPerformed
        Connection connection;
        PreparedStatement ps;
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_testkoneksi?zeroDateTimeBehavior=convertToNull",
                    "root","");
            ps = connection.prepareStatement("SELECT 'username', 'password' FROM 'tb_login' WHERE 'username' = ? AND 'password' = ?");
            ps.setString(1, tfuname.getText());
            ps.setString(2, tfpw.getText());
            ResultSet result = ps.executeQuery();
            if(result.next()){
                new frmMain().show();
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Salah!");
                tfpw.setText("");
                tfuname.requestFocus();
            }
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
        }
    }//GEN-LAST:event_bsigninActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void bsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsignupActionPerformed
        String username = tfuname.getText();
        String password = tfpwd.getText();
        
        try{
            try (Statement statement = (Statement) file_koneksi.GetConnection().createStatement()){
                statement.executeUpdate("insert into tb_login(username, password VALUES ('"+username+"','"+password+"');");
            }
            JOptionPane.showMessageDialog(null, "Selamat! anda berhasil Sign Up!");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Mohon maaf, ulangi lagi prosedur");
        }
    }//GEN-LAST:event_bsignupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton bsignin;
    private javax.swing.JButton bsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfpwd;
    private javax.swing.JTextField tfuname;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
