/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmotor;

import java.sql.Date;
import java.text.DateFormat;
import java.text.MessageFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sakinah
 */
public class rentmain extends javax.swing.JPanel {

    /**
     * Creates new form rentmain
     */
    public rentmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        tfstruk = new javax.swing.JTextField();
        tfnopol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        bsave = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        tfpinjam = new com.toedter.calendar.JDateChooser();
        tfkembali = new com.toedter.calendar.JDateChooser();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RENTAL MOTOR 101");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 10, 240, 50);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 80);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(null);

        jLabel2.setText("Nama");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 60, 20);

        jLabel3.setText("Alamat");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 20);

        jLabel4.setText("No. Struk");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 110, 60, 20);

        jLabel5.setText("NoPol");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 20);

        jLabel6.setText("Tanggal Pinjam");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(430, 30, 90, 20);

        jLabel7.setText("Tanggal Kembali");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(430, 70, 90, 20);
        jPanel2.add(tfnama);
        tfnama.setBounds(130, 20, 180, 30);
        jPanel2.add(tfalamat);
        tfalamat.setBounds(130, 60, 180, 30);
        jPanel2.add(tfstruk);
        tfstruk.setBounds(130, 100, 180, 30);
        jPanel2.add(tfnopol);
        tfnopol.setBounds(130, 140, 180, 30);

        jLabel8.setText("Harga Total");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(430, 100, 80, 30);
        jPanel2.add(tfharga);
        tfharga.setBounds(580, 100, 180, 30);

        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel2.add(bsave);
        bsave.setBounds(390, 150, 80, 23);

        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel2.add(bclear);
        bclear.setBounds(500, 150, 80, 23);

        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(bdelete);
        bdelete.setBounds(610, 150, 80, 23);

        bprint.setText("PRINT");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });
        jPanel2.add(bprint);
        bprint.setBounds(720, 150, 80, 23);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "NoStruk", "NoPol", "TglPinjam", "TglKembali", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 810, 220);
        jPanel2.add(tfpinjam);
        tfpinjam.setBounds(580, 20, 180, 30);
        jPanel2.add(tfkembali);
        tfkembali.setBounds(580, 60, 180, 30);

        add(jPanel2);
        jPanel2.setBounds(0, 80, 850, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        if("".equals(tfnama.getText())||"".equals(tfalamat.getText())||"".equals(tfstruk.getText())||
                "".equals(tfnopol.getText())||"".equals(tfpinjam.getText())||"".equals(tfkembali.getText())||"".equals(tfharga.getText())){
            JOptionPane.showMessageDialog(this, "Harap mengisi data dengan lengkap", "Error", JOptionpane.WARNING_MESSAGE);
        } else{
            String SQL = "INSERT INTO tb_rent (nama,alamat,nostruk,nopol,tglpinjam,tglkembali,totalharga)"
                    +"VALUES('"+tfnama.getText()"','"+tfalamat.getText()"','"+tfstruk.getText()"','"+tfnopol.getText()"',""'"+tfpinjam.getText()"','"+tfkembali.getText()"','"+tfharga.getText()"')";
                    int status  = KoneksiDB.execute(SQL);
                    if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                    }   else {
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        tfnama.setText("");
        tfalamat.setText("");
        tfstruk.setText("");
        tfnopol.setText("");
        tfpinjam.setDate(null);
        tfkembali.setDate(null);
        tfharga.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        int baris = tb_rent.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(null,"Anda yakin ingin menghapus data?","Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == 0){
            if(baris != -1){
                String struk = tb_rent.getValueAt(baris, 2).toString();
                String SQL = "DELETE FROM db_rental WHERE struk='"+struk+"'";
                int status = koneksiDB.execute(SQL);
                
                if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            } else {
               JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
            tb_rent.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bprintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bprint;
    private javax.swing.JButton bsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfharga;
    private com.toedter.calendar.JDateChooser tfkembali;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnopol;
    private com.toedter.calendar.JDateChooser tfpinjam;
    private javax.swing.JTextField tfstruk;
    // End of variables declaration//GEN-END:variables
}
